[build]
  command = "pip install --upgrade pip && pip install setuptools wheel && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"
  
[build.environment]
  # Set this in Netlify dashboard, not here
  # GEMINI_API_KEY = "AIzaSyC18Of3Op1pYFkvbs0hybRMhJmYiDJSV2A"
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  PYTHON_VERSION = "3.11"

# Add plugins
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/**/*.ts", "src/**/*.tsx"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https:;" 