[build]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[dev]
  publish = "."
  functions = "netlify/functions"
  
[build.environment]
  # Set this in Netlify dashboard, not here
  # GEMINI_API_KEY = "AIzaSyC18Of3Op1pYFkvbs0hybRMhJmYiDJSV2A"

# Add plugin to install function dependencies automatically
[[plugins]]
package = "@netlify/plugin-functions-install-core" 